name: remote_dart_analysis
description: The Dart analysis server in a Cloud Run instance via websockets.
version: 0.0.0-a1
publish_to: none
repository: https://github.com/enspyrco/remote_dart_analysis

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
